CREATE TABLE price_shows
(
    id BIGINT(11) NOT NULL AUTO_INCREMENT,
    show_id  BIGINT (11) NOT NULL,
    price_id BIGINT (11) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (show_id) REFERENCES shows (id) ON DELETE CASCADE,
    FOREIGN KEY (price_id) REFERENCES prices (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
